version: '3.0'
services:
    solr:
        build: .
        image: my_solr:5.5
        #restart: always
        ports:
            - "8983:8983"
        volumes:
            - /home/docker/solr-home:/opt/solr/solr-home
        container_name: my_solr
        privileged: true

networks:
    default:
        external:
            name: mynet
