version: '3.0'
services:
    solr:
        image: solr:5.5-alpine
        ports:
            - "8983:8983"
        volumes:
            - /home/younng/solr/solr-home/core1:/opt/solr/server/solr/core1
        container_name: solr5.5
        privileged: true

networks:
    default:
        external:
            name: mynet
